import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import test from 'node:test'

const diagnosticsDir = dirname(fileURLToPath(import.meta.url))
const srcDir = dirname(diagnosticsDir)
const repoRoot = dirname(srcDir)

function readRepoFile(path: string) {
  return readFileSync(join(repoRoot, path), 'utf8')
}

test('artwork frame material contract records steel surface and parity gates', () => {
  const contract = readRepoFile('docs/ARTWORK_FRAME_MATERIAL_CONTRACT.md')
  const docsMap = readRepoFile('docs/README.md')

  assert.match(contract, /Directional grain/)
  assert.match(contract, /dense micro-scale/)
  assert.match(contract, /irregular spacing/)
  assert.match(contract, /varied strand widths/)
  assert.match(contract, /subtle waviness/)
  assert.match(contract, /interrupted starts\/stops/)
  assert.match(contract, /overlaps or intersections/)
  assert.match(contract, /Fine scratches and gouges/)
  assert.match(contract, /scratch and gouge path population/)
  assert.match(contract, /not\s+only layer opacity/)
  assert.match(contract, /Scratch normal highlight and shadow response/)
  assert.match(contract, /vary\s+along anchored scratch fragments/)
  assert.match(contract, /without moving the scratch geometry/)
  assert.match(contract, /not be represented as single-thickness centerline strokes alone/)
  assert.match(contract, /closed tapered trough geometry/)
  assert.match(contract, /opposite physical edges/)
  assert.match(contract, /hairline-thin,\s+hard-edged,\s+and\s+unblurred/)
  assert.match(contract, /not\s+broad semi-transparent brush smudges/)
  assert.match(contract, /Gouges may be wider and\s+sparser than scratches/)
  assert.match(contract, /filled cut geometry,\s+hard edges/)
  assert.match(contract, /instead of blurred brush-stroke AO/)
  assert.match(contract, /Machining bands/)
  assert.match(contract, /Cloudy abrasion/)
  assert.match(contract, /mottled,\s+broken,\s+and\s+bounded/)
  assert.match(contract, /do not read as a few long rounded translucent brush strokes/)
  assert.match(contract, /Scuffed low-polish cross-scratches/)
  assert.match(contract, /filled trough geometry/)
  assert.match(contract, /separate light-catching rim response/)
  assert.match(contract, /not blurred or rounded brush marks/)
  assert.match(contract, /stage-gated around low polish/)
  assert.match(contract, /Roughness\/pitting\/dents/)
  assert.match(contract, /faceted impact pockets/)
  assert.match(contract, /dense micro-scale jagged\s+cavities/)
  assert.match(contract, /dark centers and crisp rim catches/)
  assert.match(contract, /not round dots or soft\s+smudges/)
  assert.match(contract, /filled hard-edged\s+pocket masks/)
  assert.match(contract, /paired\s+rim highlight\/rim shadow offsets/)
  assert.match(contract, /Pit AO,\s+rim highlight,\s+and rim shadow layers must share one fixed\s+pocket geometry/)
  assert.match(contract, /must not be translated copies of the closed\s+pocket mask/)
  assert.match(contract, /rather\s+than\s+blurred translucent brush marks/)
  assert.match(contract, /Gloss streaks/)
  assert.match(contract, /Light\/dark catch bands/)
  assert.match(contract, /Anisotropic lighting response/)
  assert.match(contract, /soft,\s+blurred,\s+low-frequency/)
  assert.match(contract, /gradient-like washes/)
  assert.match(contract, /not visible stroke clusters/)
  assert.match(contract, /stable steel grain direction while changing intensity/)
  assert.match(contract, /without reading\s+as large drawn lines/)
  assert.match(contract, /must not rotate steel grain/)
  assert.match(contract, /`metalBrushAngle` value is the user-owned material direction control/)
  assert.match(contract, /Polish must not rotate those paths\s+implicitly/)
  assert.match(contract, /Scratch,\s+gouge,\s+dent,\s+and pit rim offsets are material-anchored/)
  assert.match(contract, /does\s+not slide around when lighting changes/)
  assert.match(contract, /lighting may\s+modulate their opacity/)
  assert.match(contract, /stable per-fragment response bands/)
  assert.match(contract, /fragment paths and rim offsets\s+remain\s+anchored/)
  assert.match(contract, /Pit rim response must keep the same perimeter segment paths/)
  assert.match(contract, /must\s+not move the pocket floor,\s+rim highlight,\s+or rim shadow relative to one another/)
  assert.match(contract, /Hemisphere Light Editor And Light-Vector Shading/)
  assert.match(contract, /circular guide\s+centered on the artwork being edited/)
  assert.match(contract, /transient light override/)
  assert.match(contract, /editor-only pillar-shadow guide/)
  assert.match(contract, /bottom-right sun\s+casts the guide shadow toward top-left/)
  assert.match(contract, /not\s+exported/)
  assert.match(contract, /not saved as project JSON/)
  assert.match(contract, /center of the circle produces overhead light:\s+`\{ x: 0, y: 0, z: 1 \}`/)
  assert.match(contract, /Halfway from center to the radius produces a 45-degree inclination/)
  assert.match(contract, /radius edge produces a 90-degree grazing light/)
  assert.match(contract, /Positions outside the radius are clamped/)
  assert.match(contract, /angular position around the circle\s+maps to the horizontal light direction/)
  assert.match(contract, /normalized 3D light vector/)
  assert.match(contract, /Intended Material Direction Contract \(Pending Fix\)/)
  assert.match(contract, /current visual direction mapping has not yet been accepted/)
  assert.match(contract, /Center sun means overhead\s+neutral light/)
  assert.match(contract, /handle side as the broad shadow side/)
  assert.match(contract, /opposite side as the broad lit side/)
  assert.match(contract, /Bottom-left handle:\s+brightest broad response at the top-right,\s+strongest broad\s+shadow at the bottom-left/)
  assert.match(contract, /Bottom-right handle:\s+brightest broad response at the top-left,\s+strongest broad\s+shadow at the bottom-right/)
  assert.match(contract, /Top-left handle:\s+brightest broad response at the bottom-right,\s+strongest broad\s+shadow at the top-left/)
  assert.match(contract, /Top-right handle:\s+brightest broad response at the bottom-left,\s+strongest broad\s+shadow at the top-right/)
  assert.match(contract, /not\s+be cited as material visual\s+acceptance/)
  assert.match(contract, /legacy `metalLightAngle` slider and scalar-angle renderer path are removed/)
  assert.match(contract, /normalization tolerates\s+that field but drops it/)
  assert.match(contract, /descriptor uses overhead light\s+`\{ x: 0, y: 0, z: 1 \}`/)
  assert.match(contract, /light vector is a shading input only/i)
  assert.match(contract, /must not change steel finish fields,\s+corrosion fields,\s+derived maps,\s+height,\s+normals,\s+AO,\s+roughness,\s+gloss,\s+metal exposure/)
  assert.match(contract, /Frame-Space Macro Lighting/)
  assert.match(contract, /avoid uniform full-surface darkening/)
  assert.match(contract, /Micro-normal lighting still\s+responds to scratches,\s+pits,\s+grain,\s+flakes,\s+pores,\s+and height-map details/)
  assert.match(contract, /frame-space macro light field/)
  assert.match(contract, /`macroDiffuse`,\s+`macroShadow`,\s+`nearLightRamp`,\s+`farShadowRamp`,\s+and\s+`grazingStrength`/)
  assert.match(contract, /per-pixel position relative to the artwork\/frame center/)
  assert.match(contract, /Overhead light returns neutral broad lighting/)
  assert.match(contract, /45-degree off-center light creates a moderate\s+near-side lift and far-side shadow/)
  assert.match(contract, /grazing edge light strengthens the\s+directional split and contact-shadow response/)
  assert.match(contract, /macro field is a final-shading response only/)
  assert.match(contract, /must not change steel finish\s+fields,\s+corrosion fields,\s+derived maps/)
  assert.match(contract, /saved project schema/)
  assert.match(contract, /Preview and export\s+consume the same macro-light shading context and final shaded pixels/)
  assert.match(contract, /Height-map self-shadowing is implemented/)
  assert.match(contract, /Overhead light produces minimal directional\s+shadowing/)
  assert.match(contract, /45-degree light produces moderate contact shadows/)
  assert.match(contract, /grazing light\s+can produce longer directional darkening/)
  assert.match(contract, /macro `farShadowRamp`\/`grazingStrength` factors/)
  assert.match(contract, /Macro-lighting tests proving overhead neutrality/)
  assert.match(contract, /side\/grazing light creates a measurable near\/far luma delta/)
  assert.doesNotMatch(contract, /Planned Frame-Space Macro Lighting/)
  assert.doesNotMatch(contract, /Planned behavior,\s+not yet implemented:\s+the current canvas steel lighting path/)
  assert.match(contract, /OffscreenCanvas support is implemented as an optional renderer adapter/)
  assert.match(contract, /Capability detection records OffscreenCanvas,\s+Worker,\s+ImageBitmap,\s+and main-thread Canvas 2D availability/)
  assert.match(contract, /falls back to the main-thread Canvas 2D renderer/)
  assert.match(contract, /worker-shading adapter sends precomputed map buffers/)
  assert.match(contract, /falls back to\s+the synchronous software shading pass/)
  assert.match(contract, /Cache boundaries are split by role/)
  assert.match(contract, /Geometry cache keys must exclude the light vector and any\s+legacy scalar-angle input/)
  assert.match(contract, /shaded-pixel cache keys include final-pixel inputs/)
  assert.match(contract, /Interaction-preview quality caps texture size/)
  assert.match(contract, /WebGL remains a pivot criterion,\s+not an active renderer/)
  assert.match(contract, /consumes the same stable procedural maps as textures/)
  assert.match(contract, /avoids a\s+separate preview-only,\s+export-only,\s+or 3D-scene material implementation/)
  assert.match(contract, /old vector steel polish\/material layer\s+source is removed/)
  assert.match(contract, /depth and profile response must be clipped/)
  assert.match(contract, /cannot draw a halo outside\s+the\s+border/)
  assert.match(contract, /not to a second vector shadow pass/)
  assert.match(contract, /Material-specific tarnish/)
  assert.match(contract, /not a universal darkness or rust slider/)
  assert.match(contract, /Steel and black iron should\s+show orange\/brown rust progression/)
  assert.match(contract, /copper should move from dark oxide toward\s+blue-green patina/)
  assert.match(contract, /brass and bronze should form muted brown\/green patina/)
  assert.match(contract, /chrome should dull and pit rather than rust/)
  assert.match(contract, /gold should remain mostly\s+resistant/)
  assert.match(contract, /early oxidation speckles to patches/)
  assert.match(contract, /exposed-metal islands/)
  assert.match(contract, /metalPolish.*finish\s+continuum/s)
  assert.match(contract, /pale scuffed sheet metal/)
  assert.match(contract, /diffuse pale worn\s+steel lift/)
  assert.match(contract, /not\s+simply rough damage with higher opacity/)
  assert.match(contract, /50% as the required visual anchor/)
  assert.match(contract, /raw brushed steel/)
  assert.match(contract, /dull,\s+damaged\s+grey steel/)
  assert.match(contract, /restrained\s+micro-pitting/)
  assert.match(contract, /bright polished\s+stainless steel/)
  assert.match(contract, /near-mirror finish/)
  assert.match(contract, /current renderer baseline audit/)
  assert.match(contract, /0% reads too black and\s+cratered/)
  assert.match(contract, /50% is darker than 25%/)
  assert.match(contract, /pit coverage remains effectively unchanged/)
  assert.match(contract, /high-polish lighting still dims too much/)
  assert.match(contract, /stronger\s+normal-map-style offsets/)
  assert.match(contract, /suppressed damage depth/)
  assert.match(contract, /broader coherent reflection veils/)
  assert.match(contract, /At 100% polish/)
  assert.match(contract, /must not cut through\s+smooth\s+diffuse or specular gradients as isolated bright lines/)
  assert.match(contract, /softened into a sheen/)
  assert.match(contract, /`metalBrushAngle` stores the\s+user-selected grain direction/)
  assert.match(contract, /broad,\s+blurred,\s+low-frequency\s+reflection veils/)
  assert.match(contract, /faint vertical tonal bands/)
  assert.match(contract, /50% polish:\s+the source-of-truth raw brushed steel baseline/)
  assert.match(contract, /medium\s+stainless-grey value/)
  assert.match(contract, /Satin\/high polish.*growing brighter and more reflective/s)
  assert.match(contract, /Polish response should not be implemented as unrelated brightness islands/)
  assert.match(contract, /roughness should generally decrease/)
  assert.match(contract, /gloss and coherent reflection should generally increase/)
  assert.match(contract, /should\s+not get darker at the brushed 50% anchor than it was at the scuffed 25%\s+region/)
  assert.match(contract, /`metalTarnish` remains one saved slider/)
  assert.match(contract, /selected by `metalType`/)
  assert.match(contract, /rather than fading in one flat overlay/)
  assert.match(contract, /Rust-specific colors and flaking are valid for steel and black iron only/)
  assert.match(contract, /artworkFrameMaterialSeed\.ts/)
  assert.match(contract, /ArtworkFrameMaterialSeed/)
  assert.match(contract, /`algorithm`,\s+`key`,\s+and `seed32`/)
  assert.match(contract, /artworkFrameMaterialPlan\.ts/)
  assert.match(contract, /artworkFrameMaterialLightEditor\.ts/)
  assert.match(contract, /editor-only pillar-shadow\s+direction math/)
  assert.match(contract, /artworkFrameCorrosionField\.ts/)
  assert.match(contract, /artworkFrameCorrosionMaps\.ts/)
  assert.match(contract, /artworkFrameMaterialCanvas\.ts/)
  assert.match(contract, /old vector steel polish\/material layer\s+source is removed/)
  assert.match(contract, /There is no vector material fallback/)
  assert.match(contract, /canvas texture\s+descriptor/)
  assert.match(contract, /edge\s+exposure,\s+defect exposure,\s+moisture basins/)
  assert.match(contract, /cellular\s+pit\s+centers,\s+protected\s+metal islands/)
  assert.match(contract, /tarnish-driven stage coverage/)
  assert.match(contract, /albedo,\s+height,\s+ambient occlusion,\s+roughness,\s+metal exposure/)
  assert.match(contract, /pore masks,\s+crack masks,\s+and flake masks/)
  assert.match(contract, /computes normals\s+from height gradients/)
  assert.match(contract, /applies the descriptor light vector only during\s+software lighting passes/)
  assert.match(contract, /Canvas Material Transition/)
  assert.match(contract, /hybrid SVG geometry plus canvas material\s+textures/)
  assert.match(contract, /not saved project state/)
  assert.match(contract, /corrosion-field request/)
  assert.match(contract, /single seed source of truth/)
  assert.match(contract, /`sha256-image-v1`/)
  assert.match(contract, /Web Crypto SHA-256/)
  assert.match(contract, /`fallback-v1`/)
  assert.match(contract, /same typed `ArtworkFrameMaterialSeed` shape/)
  assert.match(contract, /no material seed is available/)
  assert.match(contract, /deterministic\s+frame-derived seed inputs/)
  assert.match(contract, /material seed key/)
  assert.match(contract, /fixed\s+polish-independent anchor/)
  assert.match(contract, /fixed\s+bounds-independent reference anchor/)
  assert.match(contract, /Actual preview\/export bounds width and\s+height,\s+texture field dimensions,\s+expanded sampling bounds,\s+`frame\.width`,\s+derived `strokeWidth`,\s+and `metalBrushAngle` are not corrosion seed inputs/)
  assert.match(contract, /Corrosion geometry seeds must exclude `metalPolish`,\s+`metalTarnish`,\s+the\s+material light vector,\s+any legacy scalar-angle input,\s+`metalBrushAngle`,\s+`frame\.width`,\s+and derived `strokeWidth`/)
  assert.match(contract, /Changing polish must not move corrosion placement masks/)
  assert.match(contract, /Changing tarnish\s+must not reseed placement/)
  assert.match(contract, /Changing the light vector must not change\s+fields or derived maps/)
  assert.match(contract, /Changing brush\s+angle may rotate\/render the steel finish,\s+but not rust placement/)
  assert.match(contract, /Changing\s+frame width may change the visible ring mask/)
  assert.match(contract, /corrosion sites that remain\s+inside the frame must stay anchored/)
  assert.match(contract, /sample continuous canonical material coordinates/)
  assert.match(contract, /instead of re-rolling per-pixel hashes/)
  assert.match(contract, /Non-geometry response inputs/)
  assert.match(contract, /`metalPolish` controls finish response/)
  assert.match(contract, /`metalTarnish` controls rust stage\s+coverage/)
  assert.match(contract, /descriptor light vector controls the\s+lighting pass/)
  assert.match(contract, /Derived rust maps must also remain independent from the material light vector/)
  assert.match(contract, /Software shading may change final pixels/)
  assert.match(contract, /Ring-based metal frames are the first supported canvas-texture target/)
  assert.match(contract, /Content-traced stroke frames may also use a canvas material texture/)
  assert.match(contract, /stroke-clipped descriptor/)
  assert.match(contract, /matching descriptors,\s+deterministic cache keys,\s+matching corrosion maps/)
  assert.match(contract, /matching material seed keys/)
  assert.match(contract, /matching final shaded pixels/)
  assert.match(contract, /Preview And Export Parity/)
  assert.match(contract, /Steel and black-iron canvas corrosion descriptors/)
  assert.match(contract, /material seed,\s+geometry seed key/)
  assert.match(contract, /Flake-stage derived maps/)
  assert.match(contract, /Final shaded pixels produced by `renderArtworkFrameCanvasMaterialTexture`/)
  assert.match(contract, /Canvas-material preview and PNG export both consume/)
  assert.match(contract, /shared canvas material renderer/)
  assert.match(contract, /same\s+`ArtworkFrameMaterialSeed` for the same source image/)
  assert.match(contract, /no preview-only or export-only corrosion seed path/)
  assert.match(contract, /Image-derived material seeds are not saved as project fields/)
  assert.match(contract, /same image seed and same frame produce\s+identical scalar fields/)
  assert.match(contract, /different image seeds move actual corrosion fields/)
  assert.match(contract, /polish changes keep placement masks stable/)
  assert.match(contract, /tarnish changes stage coverage\s+without reseeding placement/)
  assert.match(contract, /light-vector changes keep fields\/maps stable\s+while changing shaded pixels/)
  assert.match(contract, /preview\/export descriptors produce matching\s+corrosion maps from the same seed/)
  assert.doesNotMatch(contract, /steel-machining-height-shadow/)
  assert.doesNotMatch(contract, /steel-scratch-ambient-occlusion-map/)
  assert.doesNotMatch(contract, /steel-anisotropic-shadow-band/)
  assert.match(contract, /Steel and black-iron rust is no longer emitted/)
  assert.match(contract, /previous SVG rust layer stack was removed/)
  assert.match(contract, /canvas corrosion\s+renderer is the only rust source/)
  assert.match(contract, /albedo/)
  assert.match(contract, /height/)
  assert.match(contract, /ambientOcclusion/)
  assert.match(contract, /roughness/)
  assert.match(contract, /metalExposure/)
  assert.match(contract, /poreMask/)
  assert.match(contract, /crackMask/)
  assert.match(contract, /flakeMask/)
  assert.match(contract, /flakeBodyMask/)
  assert.match(contract, /flakeLipMask/)
  assert.match(contract, /flakeRootMask/)
  assert.match(contract, /flakeUndercutAO/)
  assert.match(contract, /flakeLiftHeight/)
  assert.match(contract, /flakeCurlX/)
  assert.match(contract, /flakeCurlY/)
  assert.match(contract, /flakeCastShadow/)
  assert.match(contract, /Lifted flake channels have specific roles/)
  assert.match(contract, /`flakeBodyMask` is the stable irregular rust-scale plate body/)
  assert.match(contract, /`flakeLipMask` is the thin lifted edge/)
  assert.match(contract, /must not become a uniform outline around every rust patch/)
  assert.match(contract, /`flakeRootMask` is the attached side/)
  assert.match(contract, /`flakeUndercutAO` is the dark contact cavity/)
  assert.match(contract, /`flakeLiftHeight` records positive relief/)
  assert.match(contract, /`flakeCurlX` and `flakeCurlY` are stable curl-bias inputs/)
  assert.match(contract, /`flakeCastShadow` is a stable shadow input/)
  assert.match(contract, /finite-difference software pass/)
  assert.match(contract, /`normalX`,\s+`normalY`,\s+and `normalZ`/)
  assert.match(contract, /material light vector is applied only\s+in final shading/)
  assert.match(contract, /must not change flake bodies,\s+lips,\s+roots,\s+undercuts/)
  assert.match(contract, /Rust scale is high roughness and low gloss/)
  assert.match(contract, /Metallic highlights are allowed only where `metalExposure`/)
  assert.match(contract, /Exposed steel chips are part of the rust material state/)
  assert.match(contract, /straight eraser lines through rust/)
  assert.match(contract, /restore localized metallic response/)
  assert.doesNotMatch(contract, /rust-[a-z-]+-(?:map|mask)/)
  assert.doesNotMatch(contract, /metal-aging-oxidation-speckle-map/)
  assert.doesNotMatch(contract, /metal-aging-\*/)
  assert.match(contract, /old generic vector metal-aging layer source is removed/)
  assert.match(contract, /must not be implemented by restoring the deleted vector aging overlay stack/)
  assert.match(contract, /STEEL_POLISH_STAGE_MODEL\.md/)
  assert.match(contract, /stable finish fields/)
  assert.match(contract, /derived\s+albedo\/height\/AO\/roughness\/gloss\/anisotropy maps/)
  assert.match(contract, /finite-difference normals/)
  assert.match(contract, /light-only software shading/)
  assert.match(contract, /old vector steel polish\/material layer\s+source is removed/)
  assert.match(contract, /artworkFrameSteelFinish\.ts/)
  assert.match(contract, /owns deterministic steel and\s+black-iron polish fields/)
  assert.match(contract, /finite-difference\s+normals from `steelHeight`/)
  assert.match(contract, /`metalPolish` changes response maps and final pixels over stable placement\s+masks/)
  assert.match(contract, /Current steel canvas polish derived map channels/)
  assert.match(contract, /steel albedo,\s+height,\s+ambient\s+occlusion,\s+roughness,\s+gloss,\s+metalness,\s+anisotropy/)
  assert.match(contract, /machining groove\/ridge masks/)
  assert.match(contract, /scratch and\s+gouge troughs,\s+dent and pit pockets/)
  assert.match(contract, /scuffed cross-scratch trough\s+and rim masks/)
  assert.match(contract, /Steel finish geometry seeds follow the same separation/)
  assert.match(contract, /must not reroll base\s+scratch,\s+gouge,\s+dent,\s+pit,\s+machining,\s+abrasion cloud,\s+or reflection-mask\s+placement/)
  assert.match(contract, /Steel polish canvas tests proving/)
  assert.match(contract, /brush-angle direction changes\s+without defect reseeding/)
  assert.match(contract, /smooth\s+high-polish reflection veils/)
  assert.doesNotMatch(contract, /Future canvas polish work/)
  assert.doesNotMatch(contract, /Planned steel canvas polish/)
  assert.doesNotMatch(contract, /once the polish renderer is implemented/)
  assert.doesNotMatch(contract, /md5/i)
  assert.match(docsMap, /ARTWORK_FRAME_MATERIAL_CONTRACT\.md/)
  assert.match(docsMap, /STEEL_POLISH_STAGE_MODEL\.md/)
})

test('canvas steel material path has no legacy vector material source', () => {
  const previewSource = readRepoFile(
    'src/components/preview/ArtworkFrameOverlay.tsx',
  )
  const exportSource = readRepoFile('src/export/drawArtworkFrame.ts')
  const planSource = readRepoFile('src/render/artworkFrameMaterialPlan.ts')
  const canvasSource = readRepoFile('src/render/artworkFrameMaterialCanvas.ts')
  const frameSource = readRepoFile('src/render/artworkFrame.ts')
  const sources = [
    previewSource,
    exportSource,
    planSource,
    canvasSource,
    frameSource,
  ]
  const deletedSymbols = [
    /getMetalArtworkFrameSurfaceLayers/,
    /getSteelArtworkFrameSurfaceLayers/,
    /MetalArtworkFrameSurfaceLayer/,
    /vectorSurfaceLayers/,
    /surfaceLayers/,
    /drawSteelFrameSurface/,
    /drawMetalFramePattern/,
    /MetalArtworkFramePatternDef/,
    /MetalArtworkFrameDefs/,
    /function MetalArtworkFrameRing/,
    /function MetalArtworkFrameStrokeMaterial/,
    /const usesCanvasMaterial/,
    /getMetalArtworkFrameRaisedBevelBands/,
    /getMetalArtworkFrameRaisedBevelShadowLayers/,
    /MetalArtworkFrameRaisedBevel/,
    /steel-machining-height-shadow/,
    /steel-scratch-ambient-occlusion-map/,
    /steel-anisotropic-shadow-band/,
    /metal-aging-oxidation-speckle-map/,
    /basePaint/,
    /createBaseGradient/,
    /fillBaseMaterial/,
    /getMetalArtworkFramePalette/,
    /getMetalArtworkFrameGradientStops/,
    /getMetalArtworkFrameGradientVector/,
    /MetalArtworkFrameGradientStop/,
    /METAL_BASE_COLORS/,
    /METAL_TARNISH_COLORS/,
    /metal-base-gradient/,
  ]

  assert.match(previewSource, /function MetalArtworkFrameCanvasMaterial/)
  assert.match(previewSource, /renderArtworkFrameCanvasMaterialTexture/)
  assert.match(exportSource, /drawCanvasMetalFrameSurface/)
  assert.match(exportSource, /renderArtworkFrameCanvasMaterialTexture/)

  for (const source of sources) {
    for (const deletedSymbol of deletedSymbols) {
      assert.doesNotMatch(source, deletedSymbol)
    }
  }
})

test('steel rust stage model records lifted flake implementation and parity gates', () => {
  const rustModel = readRepoFile('docs/STEEL_RUST_STAGE_MODEL.md')
  const docsMap = readRepoFile('docs/README.md')

  assert.match(rustModel, /Current implemented derived channels/)
  assert.match(rustModel, /`albedo`,\s+`height`,/)
  assert.match(rustModel, /`ambientOcclusion`,\s+`roughness`,\s+`metalExposure`/)
  assert.match(rustModel, /`poreMask`,\s+`crackMask`,/)
  assert.match(rustModel, /`flakeMask`,\s+`flakeBodyMask`,\s+`flakeLipMask`/)
  assert.match(rustModel, /`flakeRootMask`,\s+`flakeUndercutAO`,\s+`flakeLiftHeight`/)
  assert.match(rustModel, /`flakeCurlX`,\s+`flakeCurlY`,\s+`flakeCastShadow`/)
  assert.match(rustModel, /`normalX`,\s+`normalY`,\s+and `normalZ`/)
  assert.match(rustModel, /older SVG rust layer stack is removed\/deprecated/)
  assert.match(rustModel, /active rust rendering for those metals is the canvas corrosion field/)
  assert.match(rustModel, /`ArtworkFrameMaterialSeed`/)
  assert.match(rustModel, /`sha256-image-v1`/)
  assert.match(rustModel, /Web Crypto SHA-256/)
  assert.match(rustModel, /stable `key` and `seed32`/)
  assert.match(rustModel, /`fallback-v1`/)
  assert.match(rustModel, /deterministic for the payload bytes and length/)
  assert.match(rustModel, /no material seed is available/)
  assert.match(rustModel, /frame-derived seed inputs/)
  assert.match(rustModel, /fixed polish-independent anchor/)
  assert.match(rustModel, /fixed\s+bounds-independent reference anchor/)
  assert.match(rustModel, /Actual preview\/export bounds width and height,\s+texture field dimensions,\s+expanded sampling bounds,\s+`frame\.width`,\s+derived\s+`strokeWidth`,\s+and `metalBrushAngle` are excluded/)
  assert.match(rustModel, /must not include `metalPolish`,\s+`metalTarnish`,\s+the material light vector,\s+any legacy scalar-angle input,\s+`metalBrushAngle`/)
  assert.match(rustModel, /`metalPolish` is a response input/)
  assert.match(rustModel, /`metalTarnish` is a stage input/)
  assert.match(rustModel, /material light vector is a shading input/)
  assert.match(rustModel, /`metalBrushAngle` is a steel-finish response input/)
  assert.match(rustModel, /`frame\.width` and derived `strokeWidth` are clipping\/visibility inputs/)
  assert.match(rustModel, /corrosion values in pixels that\s+remain inside the frame must stay anchored/)
  assert.match(rustModel, /Texture field dimensions and expanded sampling bounds are rasterization\s+inputs/)
  assert.match(rustModel, /sample continuous canonical material\s+coordinates/)
  assert.match(rustModel, /rather than re-rolling per-pixel\s+hashes/)
  assert.match(rustModel, /must not\s+reseed the underlying exposure,\s+basin,\s+pit,\s+protection,\s+or potential fields/)
  assert.match(rustModel, /Stage 5: Flaking And Undercutting/)
  assert.match(rustModel, /`flakeBodyMask`: irregular rust-scale plates/)
  assert.match(rustModel, /body contributes positive\s+height/)
  assert.match(rustModel, /`flakeLipMask`: thin lifted edges/)
  assert.match(rustModel, /stronger\s+height than ordinary flake bodies/)
  assert.match(rustModel, /rather than contour-like sticker outlines/)
  assert.match(rustModel, /`flakeRootMask`: attached plate sides/)
  assert.match(rustModel, /`flakeUndercutAO`: contact shadow and cavity darkness/)
  assert.match(rustModel, /`flakeLiftHeight`: positive lifted-scale relief/)
  assert.match(rustModel, /`flakeCurlX` and `flakeCurlY`: stable curl-bias inputs/)
  assert.match(rustModel, /`flakeCastShadow`: stable cast\/contact-shadow input/)
  assert.match(rustModel, /`metalExposure`: fresh steel chips/)
  assert.match(rustModel, /must not be seeded\s+from lighting input/)
  assert.match(rustModel, /flake lips have greater average height than flake bodies/)
  assert.match(rustModel, /undercuts have stronger AO/)
  assert.match(rustModel, /final shaded pixels change when the light vector changes/)
  assert.match(rustModel, /Stage 6: Advanced Coverage/)
  assert.match(rustModel, /`roughness`: near-total gloss suppression on rust/)
  assert.match(rustModel, /lower roughness only\s+on exposed metal chips\/ridges/)
  assert.match(rustModel, /Exposed steel islands and chips retain small metallic highlights/)
  assert.match(rustModel, /Flake lips need directional highlight/)
  assert.match(rustModel, /darker response when\s+facing away from the light/)
  assert.match(rustModel, /normal pass derives `normalX`,\s+`normalY`,\s+and `normalZ`/)
  assert.match(rustModel, /finite differences in `height`/)
  assert.match(rustModel, /material light vector may only\s+affect the software shading pass/)
  assert.match(rustModel, /must not alter corrosion fields,\s+flake\s+body\/lip\/root\/undercut maps/)
  assert.match(rustModel, /polish affects finish response over the stable geometry/)
  assert.match(rustModel, /tarnish advances\s+stage coverage over the stable geometry/)
  assert.match(rustModel, /Neither control owns the image-derived\s+seed/)
  assert.match(rustModel, /Hemisphere Light Editor For Rust/)
  assert.match(rustModel, /implemented preview light editor exposes a sun handle/)
  assert.match(rustModel, /Positions outside the radius are clamped/)
  assert.match(rustModel, /legacy `metalLightAngle` slider and scalar-angle renderer path are removed/)
  assert.match(rustModel, /normalization tolerates it but\s+drops it from active frame state/)
  assert.match(rustModel, /uses the overhead light vector\s+`\{ x: 0, y: 0, z: 1 \}`/)
  assert.match(rustModel, /override is not persisted as project state/)
  assert.match(rustModel, /Centered sun position means overhead light/)
  assert.match(rustModel, /half\s+radius is 45 degrees/)
  assert.match(rustModel, /edge is grazing light/)
  assert.match(rustModel, /Intended Rust Macro Direction Contract \(Pending Fix\)/)
  assert.match(rustModel, /not a\s+claim of accepted current visual behavior/)
  assert.match(rustModel, /Dragging the sun defines a light control vector/)
  assert.match(rustModel, /handle\s+side is the broad shadow side/)
  assert.match(rustModel, /opposite side is the broad lit side/)
  assert.match(rustModel, /Bottom-left handle:\s+brightest broad rust response at the top-right,\s+strongest broad rust shadow at the bottom-left/)
  assert.match(rustModel, /Bottom-right handle:\s+brightest broad rust response at the top-left,\s+strongest broad rust shadow at the bottom-right/)
  assert.match(rustModel, /Top-left handle:\s+brightest broad rust response at the bottom-right,\s+strongest broad rust shadow at the top-left/)
  assert.match(rustModel, /Top-right handle:\s+brightest broad rust response at the bottom-left,\s+strongest broad rust shadow at the top-right/)
  assert.match(rustModel, /must not move or reseed\s+corrosion scalar fields/)
  assert.match(rustModel, /normalized 3D light vector only in\s+the\s+final shading pass/)
  assert.match(rustModel, /pit and pore depth\s+response/)
  assert.match(rustModel, /directional\s+undercut\/contact shadows/)
  assert.match(rustModel, /must not change corrosion scalar fields,\s+derived rust maps,\s+height,\s+normals,\s+AO,\s+roughness,\s+metal exposure/)
  assert.match(rustModel, /Frame-Space Macro Lighting For Rust Composition/)
  assert.match(rustModel, /same implemented frame-space macro light field as\s+clean steel/)
  assert.match(rustModel, /in\s+addition to local micro-normal response/)
  assert.match(rustModel, /bounded macro\s+diffuse,\s+shadow,\s+near-side,\s+far-side,\s+and grazing factors/)
  assert.match(rustModel, /near-side\s+diffuse lift and far-side darkening/)
  assert.match(rustModel, /Grazing light strengthens directional falloff/)
  assert.match(rustModel, /without changing any rust geometry/)
  assert.match(rustModel, /same\s+macro-light shading context/)
  assert.match(rustModel, /Height-map self-shadowing for rust reads the stable rust height map/)
  assert.match(rustModel, /macro `farShadowRamp`\/`grazingStrength` factors/)
  assert.match(rustModel, /Overhead light produces minimal directional contact\s+shadowing/)
  assert.match(rustModel, /45-degree light\s+produces moderate shadowing/)
  assert.match(rustModel, /grazing light can\s+produce longer directional\s+darkening/)
  assert.match(rustModel, /Macro-light region diagnostics prove overhead light remains broadly neutral/)
  assert.match(rustModel, /does not move corrosion maps or flake maps/)
  assert.doesNotMatch(rustModel, /Planned Frame-Space Macro Lighting For Rust Composition/)
  assert.doesNotMatch(rustModel, /Planned behavior,\s+not yet implemented:\s+the same frame-space macro light field/)
  assert.match(rustModel, /OffscreenCanvas and worker-shading adapters are optional\s+acceleration paths/)
  assert.match(rustModel, /main-thread Canvas 2D fallback/)
  assert.match(rustModel, /WebGL remains a later pivot criterion/)
  assert.match(rustModel, /shade\s+these same rust maps as textures/)
  assert.match(rustModel, /must not\s+become a separate rust implementation/)
  assert.match(rustModel, /Preview and export consume the same canvas material descriptor/)
  assert.match(rustModel, /same\s+`ArtworkFrameMaterialSeed` for the same source image/)
  assert.match(rustModel, /geometry seed key,\s+scalar fields,\s+and derived maps must match/)
  assert.match(rustModel, /both call `renderArtworkFrameCanvasMaterialTexture`/)
  assert.match(rustModel, /Preview embeds the returned image\s+source in SVG/)
  assert.match(rustModel, /PNG export draws the returned image source/)
  assert.match(rustModel, /matching material seed keys/)
  assert.match(rustModel, /matching scalar fields/)
  assert.match(rustModel, /matching derived\s+flake maps/)
  assert.match(rustModel, /matching height\/normal\/AO\/roughness maps/)
  assert.match(rustModel, /matching final\s+shaded pixels/)
  assert.match(rustModel, /same image seed,\s+project,\s+and frame parameters/)
  assert.match(rustModel, /Different image seeds must change actual\s+corrosion geometry fields/)
  assert.match(rustModel, /deprecated SVG rust layer stack must not return/)
  assert.match(rustModel, /separate preview\/export rust systems/)
  assert.match(rustModel, /Same image seed plus the same frame produces identical corrosion scalar fields/)
  assert.match(rustModel, /Different image seeds produce different scalar corrosion geometry/)
  assert.match(rustModel, /different `metalPolish` values preserves placement masks/)
  assert.match(rustModel, /different `metalTarnish` values preserves placement\s+fields/)
  assert.match(rustModel, /different material light vectors preserves scalar fields\s+and derived maps/)
  assert.match(rustModel, /Preview\/export descriptors use the same material seed/)
  assert.match(rustModel, /Preview\/export descriptors,\s+flake maps,\s+height,\s+normals,\s+AO,\s+roughness/)
  assert.doesNotMatch(rustModel, /md5/i)
  assert.match(docsMap, /STEEL_RUST_STAGE_MODEL\.md/)
})

test('steel polish stage model records canvas finish plan and safeguards', () => {
  const polishModel = readRepoFile('docs/STEEL_POLISH_STAGE_MODEL.md')
  const docsMap = readRepoFile('docs/README.md')

  assert.match(polishModel, /Current Research Basis/)
  assert.match(polishModel, /Low polish means rough damaged steel/)
  assert.match(polishModel, /dull grey metal rather than becoming a black crater texture/)
  assert.match(polishModel, /50% polish is the required brushed-steel anchor/)
  assert.match(polishModel, /subtle micro-pitting,\s+and medium stainless-grey value/)
  assert.match(polishModel, /High polish suppresses scratch,\s+dent,\s+and pit depth/)
  assert.match(polishModel, /bright stainless and near-mirror polish/)
  assert.match(polishModel, /Current Baseline Audit/)
  assert.match(polishModel, /2026-06-28 baseline audit/)
  assert.match(polishModel, /artifacts\/steel-baseline-audit/)
  assert.match(polishModel, /Current 0% polish is too black and cratered/)
  assert.match(polishModel, /moon-surface craters/)
  assert.match(polishModel, /Current pit population is effectively constant/)
  assert.match(polishModel, /visible pit depth,\s+AO,\s+size,\s+and population must reduce with polish response/)
  assert.match(polishModel, /50% as darker than 25%/)
  assert.match(polishModel, /50% brushed anchor must not dip below/)
  assert.match(polishModel, /stronger lit-side energy and coherent reflection/)
  assert.match(polishModel, /External Research Basis/)
  assert.match(polishModel, /mechanically polished,\s+brushed and buffed/)
  assert.match(polishModel, /Surface roughness is not captured by one number alone/)
  assert.match(polishModel, /`Sa`,\s+texture direction \(`Std`\)/)
  assert.match(polishModel, /RMS slope \(`Sdq`\)/)
  assert.match(polishModel, /Microfacet BRDF research/)
  assert.match(polishModel, /Anisotropic BRDF models/)
  assert.match(polishModel, /Scratch-rendering research/)
  assert.match(polishModel, /Core Renderer Rule/)
  assert.match(polishModel, /Polish is a generated finish state,\s+not an opacity curve/)
  assert.match(polishModel, /stable finish field/)
  assert.match(polishModel, /Albedo:/)
  assert.match(polishModel, /medium stainless-grey brushed tonal striations at the 50% anchor/)
  assert.match(polishModel, /Height\/displacement:/)
  assert.match(polishModel, /shallow micro-pits/)
  assert.match(polishModel, /must be restrained enough that steel does not read as a\s+crater field/)
  assert.match(polishModel, /Normal response:/)
  assert.match(polishModel, /Ambient occlusion:/)
  assert.match(polishModel, /Roughness\/gloss:/)
  assert.match(polishModel, /Anisotropy:/)
  assert.match(polishModel, /Defect masks:/)
  assert.match(polishModel, /stable candidate features/)
  assert.match(polishModel, /visibility,\s+depth,\s+AO,\s+apparent size,\s+and response change with polish stage/)
  assert.match(polishModel, /Placement stability does not mean constant visible pit population/)
  assert.match(polishModel, /material light vector is applied only during final software shading/)
  assert.match(polishModel, /must not alter finish fields,\s+defect masks,\s+height,\s+normals,\s+AO,\s+roughness,\s+gloss,\s+anisotropy direction/)
  assert.match(polishModel, /`metalBrushAngle` may change the lay direction/)
  assert.match(polishModel, /must not\s+reseed random defect placement/)
  assert.match(polishModel, /`metalTarnish` is a separate corrosion\/aging stage input/)
  assert.match(polishModel, /Abrasion direction field/)
  assert.match(polishModel, /Machining groove field/)
  assert.match(polishModel, /Scratch\/gouge field/)
  assert.match(polishModel, /Dent\/pit field/)
  assert.match(polishModel, /Cloud abrasion field/)
  assert.match(polishModel, /Buffing\/reflection field/)
  assert.match(polishModel, /artworkFrameSteelFinish\.ts/)
  assert.match(polishModel, /owns the stable steel finish field/)
  assert.match(polishModel, /stage units,\s+derived finish maps,\s+finite-difference normals/)
  assert.match(polishModel, /finish geometry seed includes/)
  assert.match(polishModel, /excludes `metalPolish`,\s+`metalTarnish`,\s+the material light vector,\s+any legacy scalar-angle input/)
  assert.match(polishModel, /`metalBrushAngle` may be used\s+as a direction response input/)
  assert.match(polishModel, /Derived Map Channels/)
  assert.match(polishModel, /`steelAlbedo`/)
  assert.match(polishModel, /`steelHeight`/)
  assert.match(polishModel, /`steelAmbientOcclusion`/)
  assert.match(polishModel, /`steelRoughness`/)
  assert.match(polishModel, /`steelGloss`/)
  assert.match(polishModel, /`steelMetalness`/)
  assert.match(polishModel, /`steelAnisotropy`/)
  assert.match(polishModel, /`scratchTroughMask`/)
  assert.match(polishModel, /`gougeTroughMask`/)
  assert.match(polishModel, /`dentPocketMask`/)
  assert.match(polishModel, /`pitPocketMask`/)
  assert.match(polishModel, /`scuffCrossScratchTroughMask`/)
  assert.match(polishModel, /`scuffCrossScratchRimLightMask`/)
  assert.match(polishModel, /`scuffCrossScratchRimShadowMask`/)
  assert.match(polishModel, /`polishedReflectionMask`/)
  assert.match(polishModel, /Normals are derived from `steelHeight` with finite differences/)
  assert.match(polishModel, /buildArtworkFrameSteelFinishNormalInputs\(\)/)
  assert.match(polishModel, /steelFinishMaps/)
  assert.match(polishModel, /Slider Stage Bands/)
  assert.match(polishModel, /0\.00-0\.12/)
  assert.match(polishModel, /0\.10-0\.30/)
  assert.match(polishModel, /0\.28-0\.58/)
  assert.match(polishModel, /0\.54-0\.76/)
  assert.match(polishModel, /0\.72-0\.92/)
  assert.match(polishModel, /0\.88-1\.00/)
  assert.match(polishModel, /overlap by at least `0\.02`/)
  assert.match(polishModel, /Stage 0: Rough Damaged Steel/)
  assert.match(polishModel, /Stage 1: Scuffed Low Polish/)
  assert.match(polishModel, /Stage 2: Brushed Baseline/)
  assert.match(polishModel, /Stage 3: Fine Satin Polish/)
  assert.match(polishModel, /Stage 4: Semi-Bright Polish/)
  assert.match(polishModel, /Stage 5: Near-Mirror Polish/)
  assert.match(polishModel, /Dull darker grey steel/)
  assert.match(polishModel, /not black crater texture/)
  assert.match(polishModel, /50% is the visual anchor/)
  assert.match(polishModel, /Raw brushed stainless-grey steel/)
  assert.match(polishModel, /Bright stainless or near-mirror steel/)
  assert.match(polishModel, /Stage response must also avoid visible brightness oscillation/)
  assert.match(polishModel, /should not be darker than the 25%\s+scuffed-low region/)
  assert.match(polishModel, /Roughness should generally decrease and gloss\/coherent\s+reflection should generally increase/)
  assert.match(polishModel, /The lighting pass should use stable inputs/)
  assert.match(polishModel, /material light vector must not seed,\s+rotate,\s+or translate any map/)
  assert.match(polishModel, /Hemisphere Light Editor For Steel/)
  assert.match(polishModel, /implemented preview light editor exposes a sun handle/)
  assert.match(polishModel, /Positions outside the radius are clamped/)
  assert.match(polishModel, /legacy `metalLightAngle` slider and scalar-angle renderer path are removed/)
  assert.match(polishModel, /normalization tolerates it but\s+drops it from active frame state/)
  assert.match(polishModel, /use the overhead light vector\s+`\{ x: 0, y: 0, z: 1 \}`/)
  assert.match(polishModel, /override is not persisted as project state/)
  assert.match(polishModel, /Centered sun position means overhead light/)
  assert.match(polishModel, /half radius is 45 degrees/)
  assert.match(polishModel, /edge is grazing light/)
  assert.match(polishModel, /Intended Steel Macro Direction Contract \(Pending Fix\)/)
  assert.match(polishModel, /not a\s+claim of accepted current visual behavior/)
  assert.match(polishModel, /Dragging the sun defines a light control vector/)
  assert.match(polishModel, /handle\s+side is the broad shadow side/)
  assert.match(polishModel, /opposite side is the broad lit\s+side/)
  assert.match(polishModel, /Bottom-left handle:\s+brightest broad steel response at the top-right,\s+strongest broad steel shadow at the bottom-left/)
  assert.match(polishModel, /Bottom-right handle:\s+brightest broad steel response at the top-left,\s+strongest broad steel shadow at the bottom-right/)
  assert.match(polishModel, /Top-left handle:\s+brightest broad steel response at the bottom-right,\s+strongest broad steel shadow at the top-left/)
  assert.match(polishModel, /Top-right handle:\s+brightest broad steel response at the bottom-left,\s+strongest broad steel shadow at the top-right/)
  assert.match(polishModel, /must not move or reseed steel\s+finish fields/)
  assert.match(polishModel, /normalized 3D light vector only in\s+the\s+final shading pass/)
  assert.match(polishModel, /anisotropic brushed bands/)
  assert.match(polishModel, /height-map self-shadow response/)
  assert.match(polishModel, /must not\s+change the stable finish field,\s+steel derived maps,\s+height,\s+finite-difference\s+normals,\s+AO,\s+roughness,\s+gloss,\s+anisotropy direction maps/)
  assert.match(polishModel, /Frame-Space Macro Lighting For Steel/)
  assert.match(polishModel, /implemented frame-space macro light field during final\s+software shading/)
  assert.match(polishModel, /instead\s+of uniform full-surface darkening/)
  assert.match(polishModel, /Centered overhead light remains broadly neutral/)
  assert.match(polishModel, /45-degree off-center light\s+lifts the near side and darkens the far side/)
  assert.match(polishModel, /grazing edge light increases\s+directional falloff/)
  assert.match(polishModel, /High-polish steel\s+should gain lit-side energy and coherent reflection/)
  assert.match(polishModel, /rather than only lowering the entire surface value/)
  assert.match(polishModel, /Macro lighting owns broad illumination/)
  assert.match(polishModel, /must\s+not\s+reseed or move finish fields/)
  assert.match(polishModel, /saved project\s+schema/)
  assert.match(polishModel, /Height-map self-shadowing for steel reads `steelHeight`/)
  assert.match(polishModel, /macro `farShadowRamp`\/`grazingStrength` factors/)
  assert.match(polishModel, /Overhead light produces minimal directional contact\s+shadowing/)
  assert.match(polishModel, /45-degree light\s+produces moderate shadowing/)
  assert.match(polishModel, /grazing light can\s+produce longer directional\s+darkening/)
  assert.match(polishModel, /Macro-light region diagnostics prove overhead light remains broadly neutral/)
  assert.match(polishModel, /side light creates a near\/far luma split/)
  assert.doesNotMatch(polishModel, /Planned Frame-Space Macro Lighting For Steel/)
  assert.doesNotMatch(polishModel, /Planned behavior,\s+not yet implemented:\s+flat steel/)
  assert.match(polishModel, /stable steel finish fields,\s+derived maps,\s+and normal inputs\s+are cacheable/)
  assert.match(polishModel, /OffscreenCanvas and worker-shading adapters are\s+optional acceleration paths/)
  assert.match(polishModel, /main-thread Canvas 2D fallback/)
  assert.match(polishModel, /WebGL remains a later pivot criterion/)
  assert.match(polishModel, /shade these same steel maps as textures/)
  assert.match(polishModel, /not become a separate steel\s+material model/)
  assert.match(polishModel, /Implemented Pipeline/)
  assert.match(polishModel, /Material planning/)
  assert.match(polishModel, /Stable finish field/)
  assert.match(polishModel, /Stage-unit model/)
  assert.match(polishModel, /Derived maps: steel albedo,\s+height,\s+AO,\s+roughness,\s+gloss,\s+metalness/)
  assert.match(polishModel, /Normal pass/)
  assert.match(polishModel, /Shading pass/)
  assert.match(polishModel, /shadeArtworkFrameSteelFinishImageData\(\)/)
  assert.match(polishModel, /descriptor light vector,\s+`metalBrushAngle`,\s+roughness,\s+gloss/)
  assert.match(polishModel, /frame-space macro lighting,\s+and the height-map self-shadow pass only\s+during software shading/)
  assert.match(polishModel, /Rust composition/)
  assert.match(polishModel, /Rust overrides steel\s+albedo,\s+height,\s+AO,\s+roughness,\s+gloss,\s+and metal exposure/)
  assert.match(polishModel, /exposed steel chips recover localized steel finish response/)
  assert.match(polishModel, /Preview\/export parity/)
  assert.match(polishModel, /Preview and export consume the same canvas material descriptor/)
  assert.match(polishModel, /No preview-only,\s+export-only,\s+or vector\s+fallback steel material path is allowed/)
  assert.match(polishModel, /Stage units overlap and progress smoothly/)
  assert.match(polishModel, /50% brushed baseline does not\s+dip below the 25% scuffed-low region/)
  assert.match(polishModel, /visible pit depth,\s+AO,\s+apparent size,\s+and\s+population reduce with polish response/)
  assert.match(polishModel, /pitting stays shallow and micro-scale/)
  assert.match(polishModel, /Different `metalPolish` values preserve base placement fields/)
  assert.match(polishModel, /Different material light vectors preserve finish fields/)
  assert.match(polishModel, /Different `metalBrushAngle` values rotate brushed anisotropy\/tangent response/)
  assert.match(polishModel, /High-polish light diagnostics prove side and grazing light add coherent\s+lit-side energy/)
  assert.match(polishModel, /instead of primarily dimming the whole\s+surface/)
  assert.match(polishModel, /Low-polish scratches,\s+dents,\s+pits,\s+and gouges have coupled height\/AO\/normal\s+geometry/)
  assert.match(polishModel, /High-polish reflection veils remain broad and smooth/)
  assert.match(polishModel, /Do not use bitmap steel textures as the source of truth/)
  assert.match(polishModel, /Do not make polish move rust placement/)
  assert.doesNotMatch(polishModel, /should eventually expose/)
  assert.doesNotMatch(polishModel, /Implementation Phasing/)
  assert.doesNotMatch(polishModel, /md5/i)
  assert.match(docsMap, /STEEL_POLISH_STAGE_MODEL\.md/)
})
